### ISSUE TITLE
Total periods wrong?

### ISSUE THREAD

**Issue by 21orangehat** [cryptarbitrage-code/deribit-ivrank#1]
Hey!

Thank you for the tool!

I noticed that the app ask 1 year of data, but the total periods is showing 731. 

It should by 365 right?  Or maybe I'm missing something.

**Comment by cryptarbitrage-code** [comment]
No worries. I hope you find it useful. 

The resolution is currently set to 43200 seconds which is 12 hours, so double the number of periods compared to if it were daily snapshots. If you prefer daily snapshots then you could double the resolution value to 86400, which would halve the number of periods.
The resulting values for IVR and IVP will be very similar either way though, you just get a tiny bit more detail with the 12 hour data. When going for smaller resolutions, you'll need to be sure that the response from the API does actually include all the data you need. I haven't tested pulling hourly snapshots for a full year for example, which may need more than one API request.
